### ISSUE TITLE
[EPIC] Create dashboards and playbooks for existing rules for kubernetes operations

### ISSUE THREAD

**Issue by richardtief** [cloudoperators/kubernetes-operations#2]
## Context 

kubernetes-operations comes with a standard set of Prometheus alerting rules. To take action when the alert is triggered, the content of this repository should also include some step-by-step instructions on how to fix the issues. This can also be enriched with links to the main Kubernetes documentation and other operational guides to have a collection of information at hand. Additional, Plutono dashboards for Kubernetes need to be provided.

## Tasks

- [x] Create alerting rules 
- [ ] Create playbooks for alerting rules
- [ ] Create dashboards for Plutono

## References

- Create one file per playbook here: https://github.com/cloudoperators/kubernetes-operations/tree/main/playbooks
- Alerting rules can be found here: https://github.com/cloudoperators/kubernetes-operations/tree/main/charts/alerts
- Dashboards can be added here: https://github.com/cloudoperators/kubernetes-operations/tree/main/charts/dashboards
